# composite action, not to be run on its own, but included in a build script

name: 'Upload conan packages'
description: 'Uploads one or multiple conan packages, to either the public or private repository'

inputs:
  package_name:
    required: false
    default: "*"
    type: string
  private_data:
    required: false
    default: false
    type: boolean
  python_set_env_vars:
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
      - name: Upload the Package(s)
        shell: bash
        run: |
          if [[ "${{ inputs.python_set_env_vars }}" == "true" ]]; then
            pydir=""
            conandir=""
          else
            pydir=`cat pydir.txt`
            conandir="$pydir"/Scripts/
            PATH+=":$pydir"
            hash -r
            echo "Found Python for GitHub in: $pydir"
          fi

          if [ "${{ inputs.private_data }}" == "true" ]; then
            "$conandir"conan upload "${{ inputs.package_name }}" -r cura-private-conan2 -c
          else
            "$conandir"conan upload "${{ inputs.package_name }}" -r cura-conan2 -c
          fi
