# composite action, not to be run on its own, but included at the beginning of a build script

name: 'Setup the Build Environment'
description: 'Clones the required repositories, and properly sets Python and conan up'

inputs:
  repository:
    required: false
    default: ''
    type: string

  conan_user:
    required: false
    default: ''
    type: string

  conan_password:
    required: false
    default: ''
    type: string

  private_data:
    required: false
    default: false
    type: boolean

  install_system_dependencies:
    required: false
    default: false
    type: boolean

  branch:
    required: false
    default: ''
    type: string

  repository_path:
    required: false
    default: ''
    type: string

  python_set_env_vars:
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Cleanup workspace
      shell: bash
      run: |
        set -e
        find . -mindepth 1 -delete

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.repository_path }}

    - name: Checkout CuraLE_Workflows repo
      uses: actions/checkout@v4
      with:
        repository: lulzbot3d/CuraLE_Workflows
        path: CuraLE_Workflows

    - name: Setup Python and pip
      uses: actions/setup-python@v5
      id: setup-python
      with:
        update-environment: ${{ inputs.python_set_env_vars }}
        python-version: '3.13'

    - name: Install Python requirements and setup Conan environment (Bash)
      shell: bash
      run: |
        if [[ "${{ inputs.python_set_env_vars }}" == "true" ]]; then
          pydir=""
          pydirex=""
          conandir=""
        else
          pydir="$(dirname "${{ steps.setup-python.outputs.python-path }}")"
          pydirex="$pydir"/
          conandir="$pydir"/Scripts/
          PATH+=":$pydir"
          hash -r
          echo "Installed Python for GitHub in: $pydir"
        fi
        echo $pydir >> pydir.txt

        "$pydirex"python -m pip install -r CuraLE_Workflows/.github/workflows/requirements-runner.txt

        "$conandir"conan profile detect -f
        "$conandir"conan config install https://github.com/lulzbot3d/Conan_LulzBot_Config.git

        if [ "${{ inputs.conan_user }}" != "" ] && [ "${{ inputs.conan_password }}" != "" ]; then
          "$conandir"conan remote login cura-le-conan2 ${{ inputs.conan_user }} -p ${{ inputs.conan_password }}
        fi

        if [ "${{ inputs.private_data }}" == "true" ]; then
          "$conandir"conan remote enable cura-le-private-conan2
          if [ "${{ inputs.conan_user }}" != "" ] && [ "${{ inputs.conan_password }}" != "" ]; then
            "$conandir"conan remote login cura-le-private-conan2 ${{ inputs.conan_user }} -p ${{ inputs.conan_password }}
          fi
        fi

        if [ "${{ inputs.install_system_dependencies }}" == "true" ]; then
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            chmod +x CuraLE_Workflows/runner_scripts/ubuntu_setup.sh
            sudo ./CuraLE_Workflows/runner_scripts/ubuntu_setup.sh
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            chmod +x CuraLE_Workflows/runner_scripts/macos_setup.sh
            ./CuraLE_Workflows/runner_scripts/macos_setup.sh
          fi
        fi
