name: Create Conan Dependencies for MacOS

on:
  workflow_call:
    inputs:
      recipes:
        required: true
        type: string

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}
  SENTRY_TOKEN: ${{ secrets.CURAENGINELE_SENTRY_TOKEN }}

jobs:
  package-create:
    runs-on: macos-12
    defaults:
      run:
        shell: bash

    steps:
      - name: Sync pip requirements
        run: wget https://raw.githubusercontent.com/lulzbot3d/cura-le-workflows/main/.github/workflows/requirements-runner.txt

      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
          cache: pip
          cache-dependency-path: requirements-runner.txt

      - name: Install Python requirements and Create default Conan profile
        run: pip install -r requirements-runner.txt

      - name: Install Macos system requirements for building
        run: |
          mkdir -p runner_scripts
          wget https://raw.githubusercontent.com/lulzbot3d/cura-le-workflows/main/runner_scripts/macos_setup.sh -O runner_scripts/macos_setup.sh
          chmod +x runner_scripts/macos_setup.sh
          ./runner_scripts/macos_setup.sh

      - name: Create default Conan profile
        run: conan profile new default --detect

      - name: Get Conan configuration
        run: |
          conan config install https://github.com/lulzbot3d/conan-config-le.git
          conan config install https://github.com/lulzbot3d/conan-config-le.git -a "-b runner/${{ runner.os }}/${{ runner.arch }}"

      - name: Add runner credentials to cura-le remote
        run: conan user -p ${{ secrets.CONAN_PASS }} -r cura-le ${{ secrets.CONAN_USER }}

      - name: Add conancenter remote
        run: conan remote add conancenter https://center.conan.io

      - name: Install and Upload the Package(s)
        run:
          IFS=',' read -ra r_array <<< "${{inputs.recipes}}";
          for recipe in "${r_array[@]}";
          do
            conan install -r conancenter "$recipe" --build=missing --update;
            conan upload "$recipe" -r cura-le --all -c;
          done
