name: Create Conan Dependencies for Windows

on:
  workflow_call:
    inputs:
      recipes:
        required: true
        type: string

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}
  SENTRY_TOKEN: ${{ secrets.CURAENGINELE_SENTRY_TOKEN }}

jobs:
  dependencies-create:
    runs-on: windows-2022

    steps:
      - name: Sync pip requirements
        run: curl -O https://raw.githubusercontent.com/lulzbot3d/cura-le-workflows/main/.github/workflows/requirements-runner.txt

      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
          cache: pip
          cache-dependency-path: .\requirements-runner.txt

      - name: Install Python requirements and Create default Conan profile
        run: pip install -r .\requirements-runner.txt

      - name: Create default Conan profile
        run: conan profile new default --detect

      - name: Get Conan configuration
        run: |
          conan config install https://github.com/lulzbot3d/conan-config-le.git
          conan config install https://github.com/lulzbot3d/conan-config-le.git -a "-b runner/${{ runner.os }}/${{ runner.arch }}"

      - name: Add runner credentials to cura-le remote
        run: conan user -p ${{ secrets.CONAN_PASS }} -r cura-le ${{ secrets.CONAN_USER }}

      - name: Add conancenter remote
        run: conan remote add conancenter https://center.conan.io

      - name: Install the Package(s)
        run:
          foreach($recipe in "${{inputs.recipes}}".split(","))
          {
            conan install -r conancenter $recipe --build=missing --update
          }

      - name: Upload the Package(s)
        run:
          foreach($recipe in "${{inputs.recipes}}".split(","))
          {
            conan upload $recipe -r cura-le --all -c
          }
