name: unit-test

on:
  workflow_call:
    inputs:
      test_use_ctest:
        required: false
        default: false
        type: boolean

      test_use_pytest:
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  testing:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@main
        with:
          install_system_dependencies: true

      - name: Install dependencies and build unit test
        run: conan build . -s build_type=Release --build=missing --update -c tools.build:skip_test=False ${{ inputs.test_use_pytest && '-g VirtualPythonEnv' || '' }}

      - name: Run ctest-based unit test
        if: ${{ inputs.test_use_ctest }}
        run: ctest --output-junit unit_tests_results.xml
        working-directory: build/Release/tests

      - name: Run pytest-based unit test
        if: ${{ inputs.test_use_pytest }}
        run: |
          source ../build/generators/virtual_python_env.sh
          pytest --junitxml=unit_tests_results.xml
        working-directory: tests

      - name: Save PR metadata
        if: always()
        run: |
          echo ${{ github.event.number }} > pr-id.txt
          echo ${{ github.event.pull_request.head.repo.full_name }} > pr-head-repo.txt
          echo ${{ github.event.pull_request.head.ref }} > pr-head-ref.txt

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: |
            ./**/unit_tests_results.xml
            pr-id.txt
            pr-head-repo.txt
            pr-head-ref.txt
