name: Update LulzBot Forks

on:
  workflow_call:
    inputs:
      repo:
        description: 'UltiMaker repository'
        required: true
        type: string
        default: 'Cura'

      branch:
        description: 'Branch of UltiMaker repository to pull from'
        required: false
        type: string
        default: 'main'

permissions:
  contents: read

jobs:
  update-lulzbot-forks:
    name: Upload package recipe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'ulti-main'
          token: ${{ secrets.FETCH_UPSTREAM_PAT }}

      - name: Pull (Fast-Forward) upstream changes
        id: sync
        run: |
          git remote add ulti https://github.com/Ultimaker/${{ inputs.repo }}.git
          git fetch ulti

          # Check for new commits
          ULTI_HASH=$(git rev-parse "ulti/${{ inputs.branch }}")
          git fetch origin ulti-main

          if [ -z "${ULTI_HASH}" ]; then
            echo "Error fetching upstream hash."
          elif [ "$(git branch "ulti-main" --contains="${ULTI_HASH}")" ]; then
            echo "No new commits."
          else
            echo "New commits! Pulling to ulti-main."
            git pull --no-edit --ff-only ulti "${{ inputs.branch }}"
            git push origin ulti-main
            CS=$?

            if [ "${CS}" -ne 0 ]; then
              echo "Error pushing to origin."
            else
              echo "Pushed UltiMaker changes to origin."
            fi
          fi
